//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Entity.errors", typeof(errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng không được để trống.
        /// </summary>
        public static string customername_must_not_be_empty {
            get {
                return ResourceManager.GetString("customername_must_not_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được để trống.
        /// </summary>
        public static string email_cannot_be_null {
            get {
                return ResourceManager.GetString("email_cannot_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đăng nhập.
        /// </summary>
        public static string error_login_expected {
            get {
                return ResourceManager.GetString("error_login_expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuỗi tìm kiếm không được nhiều hơn 30 ký tự.
        /// </summary>
        public static string freetext_length_cannot_lagger_30 {
            get {
                return ResourceManager.GetString("freetext_length_cannot_lagger_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ.
        /// </summary>
        public static string invalid_data {
            get {
                return ResourceManager.GetString("invalid_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ.
        /// </summary>
        public static string invalid_email {
            get {
                return ResourceManager.GetString("invalid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id không hợp lệ.
        /// </summary>
        public static string invalid_id {
            get {
                return ResourceManager.GetString("invalid_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng.
        /// </summary>
        public static string invalid_username_or_pass {
            get {
                return ResourceManager.GetString("invalid_username_or_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập cmnd.
        /// </summary>
        public static string missing_cmnd {
            get {
                return ResourceManager.GetString("missing_cmnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập địa chỉ.
        /// </summary>
        public static string missing_diachi {
            get {
                return ResourceManager.GetString("missing_diachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn quận huyện.
        /// </summary>
        public static string missing_district {
            get {
                return ResourceManager.GetString("missing_district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn mã huyện.
        /// </summary>
        public static string missing_location_code {
            get {
                return ResourceManager.GetString("missing_location_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn số tiền vay.
        /// </summary>
        public static string missing_money {
            get {
                return ResourceManager.GetString("missing_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đính kèm các tập tin.
        /// </summary>
        public static string missing_must_have_files {
            get {
                return ResourceManager.GetString("missing_must_have_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập ngày nhận đơn.
        /// </summary>
        public static string missing_ngaynhandon {
            get {
                return ResourceManager.GetString("missing_ngaynhandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn đối tác.
        /// </summary>
        public static string missing_partner {
            get {
                return ResourceManager.GetString("missing_partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số điện thoại.
        /// </summary>
        public static string missing_phone {
            get {
                return ResourceManager.GetString("missing_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn sản phẩm vay.
        /// </summary>
        public static string missing_product {
            get {
                return ResourceManager.GetString("missing_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn tỉnh/thành phố.
        /// </summary>
        public static string missing_province {
            get {
                return ResourceManager.GetString("missing_province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy người dùng.
        /// </summary>
        public static string not_found_user {
            get {
                return ResourceManager.GetString("not_found_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung ghi chú không được nhiều hơn 200 ký tự.
        /// </summary>
        public static string note_length_cannot_more_than_200 {
            get {
                return ResourceManager.GetString("note_length_cannot_more_than_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không tồn tại.
        /// </summary>
        public static string notfound {
            get {
                return ResourceManager.GetString("notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không khớp.
        /// </summary>
        public static string password_not_match {
            get {
                return ResourceManager.GetString("password_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài mật khẩu phải có ít nhất 6 ký tự.
        /// </summary>
        public static string password_not_match_min_length {
            get {
                return ResourceManager.GetString("password_not_match_min_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm đang được sử dung bởi hồ sơ khác, vui lòng chọn sản phẩm khác.
        /// </summary>
        public static string product_code_inuse {
            get {
                return ResourceManager.GetString("product_code_inuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập đã tồn tại.
        /// </summary>
        public static string username_has_exist {
            get {
                return ResourceManager.GetString("username_has_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không được để trống.
        /// </summary>
        public static string username_or_password_must_not_be_empty {
            get {
                return ResourceManager.GetString("username_or_password_must_not_be_empty", resourceCulture);
            }
        }
    }
}
